// Vercel's Express detector expects a root entrypoint importing Express.
import express from "express";
// The server bundle is generated by the Vercel build command.
// @ts-expect-error Generated JavaScript has no declaration file.
import app from "./dist/app.js";

void express;
export default app;
